#!/usr/bin/env python3
"""Render current state + DB into vault/90-system/dashboards/state-snapshot.md.

Obsidian's Dataview can only see files inside the vault, so this script gives
the vault dashboards the same data the web dashboard reads — one source of
truth (state/ + data/aios.db), two views. Run it manually, from end-session,
or on a schedule:

    python3 scripts/sync_vault_views.py

Vault path comes from config/aios.json `vault_path` (default: vault/).
"""
import datetime
import json
import os
import sqlite3

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB = os.path.join(ROOT, "data", "aios.db")


def load_json(path, default=None):
    try:
        with open(path) as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return default


def read(path):
    try:
        with open(path) as f:
            return f.read().strip()
    except OSError:
        return ""


def q(con, sql, params=()):
    try:
        return con.execute(sql, params).fetchall()
    except sqlite3.Error:
        return []


def main():
    cfg = load_json(os.path.join(ROOT, "config", "aios.json")) or {}
    vault = cfg.get("vault_path", "vault")
    if not os.path.isabs(vault):
        vault = os.path.join(ROOT, vault)
    out_path = os.path.join(vault, "90-system", "dashboards", "state-snapshot.md")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    focus = read(os.path.join(ROOT, "state", "current-focus.md"))
    # strip frontmatter from the embedded focus note
    if focus.startswith("---"):
        parts = focus.split("---", 2)
        focus = parts[2].strip() if len(parts) > 2 else focus
    loops = (load_json(os.path.join(ROOT, "state", "open-loops.json"), {}) or {}).get("loops", [])

    lines = [
        "---",
        f'title: "State snapshot"',
        f'updated: "{now}"',
        "tags: [system, dashboard]",
        "status: auto-generated",
        "related: []",
        "---",
        "> [!info] Auto-generated by `scripts/sync_vault_views.py` — do not edit. "
        f"Updated {now}.",
        "",
        "## Current focus",
        focus or "_state/current-focus.md is empty_",
        "",
        "## Open loops",
    ]
    if loops:
        lines.append("| loop | status | iteration | next action |")
        lines.append("|---|---|---|---|")
        for l in loops:
            lines.append(f"| {l.get('loop','')} | {l.get('status','')} "
                         f"| {l.get('iteration','')} | {l.get('next_action','')} |")
    else:
        lines.append("_none_")

    if os.path.exists(DB):
        con = sqlite3.connect(DB)
        lines += ["", "## Open tasks (top 10)"]
        rows = q(con, "SELECT id, priority, title, project FROM tasks"
                      " WHERE status IN ('open','in_progress')"
                      " ORDER BY priority, id DESC LIMIT 10")
        if rows:
            lines.append("| # | pri | task | project |")
            lines.append("|---|---|---|---|")
            lines += [f"| {r[0]} | {r[1]} | {r[2]} | {r[3]} |" for r in rows]
        else:
            lines.append("_none_")

        lines += ["", "## Open bugs"]
        rows = q(con, "SELECT id, severity, title, report_count FROM bugs"
                      " WHERE status IN ('open','needs-info') ORDER BY severity, id LIMIT 15")
        if rows:
            lines.append("| # | sev | bug | reports |")
            lines.append("|---|---|---|---|")
            lines += [f"| BUG-{r[0]} | {r[1]} | {r[2]} | {r[3]} |" for r in rows]
        else:
            lines.append("_none_")

        lines += ["", "## Automation runs (last 5)"]
        rows = q(con, "SELECT automation, status, started_at FROM runs ORDER BY id DESC LIMIT 5")
        if rows:
            lines.append("| automation | status | started |")
            lines.append("|---|---|---|")
            lines += [f"| {r[0]} | {r[1]} | {r[2]} |" for r in rows]
        else:
            lines.append("_none_")
        con.close()

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
